# fly.toml app configuration file generated for fabriciocosati-portfolio-api on 2024-10-25T17:46:47-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fabriciocosati-portfolio-api'
primary_region = 'gig'

[build]

[env]
ENV = 'prod'
PORT = '8080'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
