name: Continuos Integration

on:
  push:
    branches:
      - master

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Configuring Workflow
        uses: actions/checkout@v3

        env:
          ENV: prod
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        
      - name: Install go dependencies
        run: |
          go mod tidy
          go mod vendor
      
      - name: Install npm dependencies
        run: |
          npm install

      - name: Install air
        run: |
          go install github.com/air-verse/air@latest
          export PATH=$PATH:$(go env GOPATH)/bin

      - name: Start Server
        run: |
          air -c .air.toml