name: Continuos Integration

on:
  push:
    branches:
      - master

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Configuring Workflow
        uses: actions/checkout@v3

      - name: Create .env
        run: |
          echo "ENV=prod" > .env
          echo "SMTP_HOST=${{ secrets.SMTP_HOST }}" >> .env
          echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> .env
          echo "SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}" >> .env
          echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> .env
          
        
      - name: Install go dependencies
        run: |
          go mod tidy
          go mod vendor
      
      - name: Install npm dependencies
        run: |
          npm install

      - name: Install air
        run: |
          go install github.com/air-verse/air@latest
          export PATH=$PATH:$(go env GOPATH)/bin

      - name: Start Server
        run: |
          mkdir -p public 
          cp -r internal/img public/
          cp -r internal/public/* public/

          echo "<!DOCTYPE html>" > public/index.html
          echo "<html><head><title>Meu Site</title></head>" >> public/index.html
          echo "<body><h1>Site Gerado com Go!</h1></body></html>" >> public/index.html

          ls public/  # Lista o conteúdo da pasta public para conferência

      - name: Deploy gh
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public